name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui-ios maui-android maccatalyst

      - name: Restore dependencies
        run: dotnet restore

      - name: Build iOS App
        run: dotnet build ./Grocery.App/Grocery.App.csproj -f net8.0-ios -c Release --no-restore

      - name: Build Mac Catalyst App
        run: dotnet build ./Grocery.App/Grocery.App.csproj -f net8.0-maccatalyst -c Release --no-restore

      - name: Run unit tests
        run: dotnet test ./Grocery.Core.Tests/Grocery.Core.Tests.csproj -c Release --no-restore --no-build